stages:
  prepare:
    cmd: python src/create_features_w_params.py
    params: 
      - features.chi2percentile
      - features.train_path
      - features.test_path
    deps:
      - data/adult.data
      - data/adult.test
      - src/create_features.py
    outs:
      - data/pipeline.pkl
      - data/processed_train_data.csv
      - data/processed_test_data.csv
