stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - data/bagpack/train.csv
      - src/preprocessing.py
    outs:
      - data/processed_train_data.csv
      - data/processed_test_data.csv
      - data/preprocessor.pkl
